### ISSUE TITLE
Reference antenna 001

### ISSUE THREAD

**Issue by ErikOsinga** [revoltek/LiLF#27]
Hi,

A bunch of scripts have the reference antenna set to CS001LBA, but since it is being used for testing LOFAR2.0 new data will crash the pipeline. It would be nice to be able to set the reference antenna with an argument, or maybe just switch the hardcoded CS001LBA to CS002LBA?

**Comment by revoltek** [comment]
This is solved in the branch LBAdevel where we use a new LoSoTo functionality that autodetects the refant
