### ISSUE TITLE
Amp DIE step fails near end in LOFAR_self pipeline

### ISSUE THREAD

**Issue by mknapp55** [revoltek/LiLF#30]
I'm running in a singularity container (pill20220805.simg) on Ubuntu 22, machine has 12 cores, 128 G RAM, GPU, large RAID with ~6 TB free.

I'm getting an error near the end of the "slow G" step.  From the logs (attached), the error occurs when two or three of the four timeslots have already finished processing.  After I got the error the first time, I rebooted my system and ran the pipeline again - I got the same error and the logs look similar, though not quite identical.

Error: 
```
2023-11-03 20:23:29 - ERROR - DP3 run problem on:
logs_pipeline-self_2023-10-31_11:59:41/TC00_solG-c0.log
Traceback (most recent call last):
  File "/home/mknapp/software/LiLF/pipelines/LOFAR_self.py", line 243, in <module>
    MSs.run('DP3 '+parset_dir+'/DP3-solG.parset msin=$pathMS sol.h5parm=$pathMS/g.h5 sol.solint='+str(120*base_solint)+' sol.nchan='+str(16*base_nchan),
  File "/home/mknapp/software/LiLF/LiLF/lib_ms.py", line 141, in run
    self.scheduler.run(check = True, maxThreads = maxThreads)
  File "/home/mknapp/software/LiLF/LiLF/lib_util.py", line 741, in run
    self.check_run(log, commandType)
  File "/home/mknapp/software/LiLF/LiLF/lib_util.py", line 813, in check_run
    raise RuntimeError(commandType+' run problem on:\n'+out)
RuntimeError: DP3 run problem on:
logs_pipeline-self_2023-10-31_11:59:41/TC00_solG-c0.log
```

Looking at the logs for each of the timeslots, three of the four look fine but TC01_solG-c0.log says "killed" right at the end.  The machine did not reboot and I was not doing anything else on it at the time.

```
Processing 899 time slots ...

0%....10.Killed
```

Any guidance would be appreciated!  The singularity container has been working great for me up until this point.  I did note that the code in this branch for this pipeline step looks a little different than what's quoted in the error message - any chance that changes since this docker/singularity image was made could be causing the issue?

[TC00_solG-c0.log](https://github.com/revoltek/LiLF/files/13259971/TC00_solG-c0.log)
[TC01_solG-c0.log](https://github.com/revoltek/LiLF/files/13259972/TC01_solG-c0.log)
[TC02_solG-c0.log](https://github.com/revoltek/LiLF/files/13259973/TC02_solG-c0.log)
[TC03_solG-c0.log](https://github.com/revoltek/LiLF/files/13259974/TC03_solG-c0.log)
[pipeline-self_2023-11-03_212042.logger.txt](https://github.com/revoltek/LiLF/files/13259969/pipeline-self_2023-11-03_21.20.42.logger.txt)

**Comment by revoltek** [comment]
Hi, this error is most likely linked to not enough free memory. I usually run the pipeline on machine with 512 GB of RAM, do you have a workstation with more memory?

**Comment by revoltek** [comment]
maybe you can try adding a "maxThreads = 1" to the "run()" call of Dp3 that runs out of memory... how many obs hrs are you doing?

**Comment by mknapp55** [comment]
I can try that.  The observation is 4 hours.  The slightly strange thing is that it appears that three of the 4 threads had finished and memory usage was actually declining when the failure occurred.  I'm working on a resource monitor so I can know exactly what the state of free memory was - hope to have that finished this week.

**Comment by mknapp55** [comment]
I increased the swap memory on my machine to 128 G and that combined with the 128 G RAM was enough to get through this step.  I'll keep in mind reducing threads for longer observations.  Thanks for your help!
